POST http://localhost:3000/login/login HTTP/1.1
content-type: application/json

{
    "login": "root",
    "password": "root"
}

GET localhost:3000/node/getOneById?id=1 HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InJvb3QiLCJpcCI6Ijo6MSIsInVybCI6Ii9sb2dpbi9sb2dpbiIsImlhdCI6MTY2NzIwNjM0MSwiZXhwIjoxNjcyMzkwMzQxfQ.n_QyxNSplPVo0uGzyfHidlCcMYwdGGjuXlktDeyYku8

